spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

cloudinary:
  cloud-name: dtkq0w2ft
  api-key: SUA_API_KEY
  api-secret: SEU_API_SECRET

server:
  port: 8080